---
format: gfm
title: "CCBR actions 🤖"
---

<!-- README.md is generated from README.qmd. Please edit that file -->

{{< include docs/badges.qmd >}}

Custom [GitHub Actions](#actions) and [example workflows](#examples)
for CCBR repositories.
View [our documentation website](https://CCBR.github.io/actions)
for implementation details.
View the [GitHub Actions docs](https://docs.github.com/en/actions)
for information on how to write and use GitHub Actions workflows.

## Examples

See [examples/](examples) for workflow examples.
You can copy these to your own repository in the `.github/workflows/` directory
and modify them for your needs.

```{python}
#| output: asis
#| echo: false
import pathlib
for path in sorted(pathlib.Path('examples').glob('*.yml')):
    print(f"- [{path.stem}]({path})")
```

## Actions

Custom actions used in our github workflows.

```{python}
#| output: asis
#| echo: false
import yaml
for action_yml in sorted(pathlib.Path().glob("*/action.yml")):
    with action_yml.open('r') as infile:
        action_meta = yaml.load(infile, Loader = yaml.FullLoader)
    name = action_meta['name']
    desc = action_meta['description']
    print(f"- [{name}]({action_yml.parent}) - {desc}")

```

## Package

`ccbr_actions` is a Python package with helper functions used by our custom GitHub Actions.
You do not need to install the package in order to use the example workflows,
as the actions install their dependencies as needed.
However, you can install the package if you wish to use it outside of GitHub Actions or contribute changes.

### Installation

{{< include docs/install.qmd >}}

View the package documentation [here](https://CCBR.github.io/actions/package).

## Help & Contributing

{{< include docs/help.qmd >}}

## Citation

{{< include docs/cite.qmd >}}

## Inspiration

This project was inspired by [r-lib/actions](https://github.com/r-lib/actions/)
and [{usethis}](https://usethis.r-lib.org/reference/github_actions.html).
Check them out for actions, workflows, and helper functions for R packages!
