name: draft-release

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: |
          Semantic version tag for next release.
          If not provided, it will be determined based on conventional commit history.
          Example: v2.5.11
        required: false
        type: string
        default: ""
      branch: release-draft

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to include tags
      - uses: actions/CCBR/actions/draft-release@main
        with:
          github-token: ${{ github.token }}
