name: label-issues-repo-name

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  add-label:
    uses: CCBR/actions/label-issue-repo-name
    with:
      github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
