# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: R-CMD-check

permissions:
  contents: read
  pull-requests: read

jobs:
  R-CMD-check:
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, r: "release" }
          - { os: ubuntu-latest, r: "oldrel-1" }

    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: CCBR/actions/install-r-pak
        with:
          versions-file: .github/package-versions.txt
          extra-packages: local::.
          needs: dev
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: CCBR/actions/install-r-pak
        with:
          versions-file: .github/package-versions.txt
          needs: dev

      - name: Good Practice checks
        shell: Rscript {0}
        run: |
          g <- goodpractice::gp()
          g
          n_failed <- length(goodpractice::failed_checks(g))
          if (n_failed > 0) {
            warning(paste(n_failed, "failed checks"))
          }

      - name: Lint
        shell: Rscript {0}
        run: lintr::lint_package()
        env:
          LINTR_ERROR_ON_LINT: false

  check: # make sure all check jobs pass. https://github.com/orgs/community/discussions/4324#discussioncomment-3477871
    runs-on: ubuntu-latest
    needs: [R-CMD-check, lint]
    if: always()
    steps:
      - name: Successful build
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
      - name: Failing build
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
