# see: https://github.com/rstudio/vetiver-python/blob/main/docs/_quarto.yml
project:
  type: website
  output-dir: _site

website:
  title: "CCBR actions"
  site-url: https://ccbr.github.io/actions
  repo-url: https://github.com/CCBR/actions
  repo-actions: [edit, issue]
  sidebar:
    - id: reference
      style: docked
      contents: "_sidebar.yml"
    - id: docs
      title: Docs
      style: docked
      contents:
        - text: Home
          href: index.qmd
        - text: GitHub ACtions
          href: actions.qmd
        - section: Python package
          href: package.qmd
          contents:
            - text: Installation
              href: install.qmd
            - text: API reference
              href: reference/index.qmd
        - section: Project information
          contents:
            - text: Citation
              href: cite.qmd
            - text: Contributing
              href: CONTRIBUTING.md
            - href: contributors.qmd
            - text: License
              href: LICENSE.md
            - text: Changelog
              href: CHANGELOG.md
  navbar:
    right:
      - sidebar:docs
      - icon: github
        href: https://github.com/CCBR/actions
        aria-label: CCBR/actions GitHub
  page-footer:
    left: |
      Created by the
      [CCR Collaborative Bioinformatics Resource](https://github.com/CCBR)

quartodoc:
  package: ccbr_actions
  parser: google
  render_interlinks: true
  sidebar: _sidebar.yml
  title: "API Reference"
  sections:
    - title: Modules
      #desc: Functions for CCBR GitHub Actions
      contents:
        - actions
        - citation
        - data
        - docs
        - release
        - util
        - versions

metadata-files:
  - _sidebar.yml

filters:
  - interlinks

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/
    # ccbr_actions:
    #   url: https://ccbr.github.io/actions/reference
    # ccbr_tools:
    #   url: https://ccbr.github.io/Tools/reference

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    code-fold: show
