# see: https://github.com/rstudio/vetiver-python/blob/main/docs/_quarto.yml
project:
  type: website
  output-dir: _site

website:
  title: "CCBR actions"
  site-url: https://ccbr.github.io/actions
  repo-url: https://github.com/CCBR/actions
  repo-actions: [edit, issue]
  sidebar:
    - id: docs
      title: Docs
      style: docked
      contents:
        - text: Home
          href: index.qmd
        - section: GitHub Actions
          href: gh-actions.qmd
          contents:
            - section: Actions
              href: actions.qmd
              contents:
                - auto: "actions/**"
            - examples.qmd
        - section: Python package
          href: package.qmd
          contents:
            - text: Installation
              href: install.qmd
            - section: API reference
              href: reference/index.qmd
              contents:
                - auto: "reference/**"
        - section: Project information
          contents:
            - text: Citation
              href: cite.qmd
            - text: Contributing
              href: CONTRIBUTING.md
            - href: contributors.qmd
            - text: License
              href: LICENSE.md
            - text: Changelog
              href: CHANGELOG.md
  navbar:
    right:
      - sidebar:docs
      - icon: github
        href: https://github.com/CCBR/actions
        aria-label: CCBR/actions GitHub

  page-footer:
    background: black
    foreground: white
    left: |
      [![](/_extensions/fnl/fnl-logo-dark.png){height=70px}](https://frederick.cancer.gov/research/science-areas/bioinformatics-and-computational-science/advanced-biomedical-computational-science)
    center: |
      Created by the
      [CCR Collaborative Bioinformatics Resource](https://github.com/CCBR)

quartodoc:
  package: ccbr_actions
  parser: google
  render_interlinks: true
  sidebar: _sidebar.yml
  title: "API Reference"
  sections:
    - title: Modules
      contents:
        - actions
        - citation
        - data
        - docs
        - release
        - util
        - versions

metadata-files:
  - _sidebar.yml

filters:
  - interlinks

interlinks:
  sources:
    python:
      url: https://docs.python.org/3/
    # ccbr_actions:
    #   url: https://ccbr.github.io/actions/reference
    # ccbr_tools:
    #   url: https://ccbr.github.io/Tools/reference

execute:
  freeze: auto
  eval: true
  echo: true

format:
  fnl-html:
    code-fold: show
