name: test

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write

jobs:
  manual-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # required to include tags
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install .[dev,test] --upgrade pip
      - name: Manual test
        shell: python {0}
        run: |
          from ccbr_actions.actions import trigger_workflow
          trigger_workflow(workflow_name='auto-format.yml', branch='trigger-fmt', repo='CCBR/actions')
        env:
          GITHUB_TOKEN: ${{ github.token }}
